### ISSUE TITLE
Understand the input data

### ISSUE THREAD

**Issue by stevietran** [mcfadd/Job_Shop_Schedule_Problem#7]
Could you explain the "pieces" parameter in class "Task"? Is this like the product quantities of a task? What it is used for in the algorithm?

**Comment by mcfadd** [comment]
@stevietran 

Yes, the pieces parameter is like the product quantities. The machine RunSpeeds are in pieces/minute.

For example, say job 1, task 1 has 200 pieces and is ran on machine 1 with a speed of 10 pieces/minute, then the makespan for running job 1, task 1 on machine 1 is 20 minutes.
